---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.cisco.com
  resources:
  - nginxoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cisco.com
  resources:
  - nginxoperators/finalizers
  verbs:
  - update
- apiGroups:
  - app.cisco.com
  resources:
  - nginxoperators/status
  verbs:
  - get
  - patch
  - update
