name: Docker

on: push

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go 1.17
        uses: actions/setup-go@v3
        with:
            go-version: '>=1.17.0'

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        run: |
          make docker-build IMG=ghcr.io/${{ github.repository }}
          make docker-push IMG=ghcr.io/${{ github.repository }}
      
